### ISSUE TITLE
Fabric 7.0 - JAR Removal - cassandra-driver-core-3.7.1

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#705]
I had noticed that when moving project from 6.5 to 7.0 a compilation error that was due to removal of a driver.
1) Could you elaborate if adding the JAR would cause a problem ?
2) Seems like the java-driver-core-4.14.1 was a replacement, does this mean I have to upgrade to Cassandra 4.0 ?

**Comment by natalylic** [comment]
There is no need to upgrade to Cassandra 4.0, since Fabric 7.0 can work with Cassandra 3.11.
Adding the JAR will resolve the compilation error but it will fail at run time. 
Our recommendation is to use the Fabric infrastructure (create an interface to Cassandra & use the DbCommand actor) to connect to Cassandra, rather than connect to it directly via your code.
